name: sisarthro_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  path: ^1.8.3
  path_provider: ^2.1.1
  http: ^1.1.2
  sqflite: ^2.3.0
  geolocator: ^13.0.2
  shared_preferences: ^2.2.2
  flutter_slidable: ^3.0.1


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/casa.png
    - assets/images/splash.png

